### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by SuperFrankyy** [cli99/flops-profiler#6]
When I try to install this pack, it requires-Python >=3.10,<4.0. Would it be able to support other versions of python, for example 3.9?
I was trying to install it under python 3.9.1, and i got the error like this:
ERROR: Ignored the following versions that require a different python version: 0.1.1 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement flops-profiler (from versions: none)
ERROR: No matching distribution found for flops-profiler

**Comment by mananrg** [comment]
You can create environments in python using venv default or conda and install all the required dependencies in it
Venv Documentation-https://docs.python.org/3/library/venv.html
Conda Documentation-https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

Hope this helps!

**Comment by SuperFrankyy** [comment]
Thanks! Creating a venv in python 3.10 will certainly work. But my question is whether it could support other versions of python. If it does, we don't have to reinstall all the other dependencies. Thanks again for your suggestion!

**Comment by cli99** [comment]
Hi @SuperFrankyy , the python version requirement is now lowered to 3.8. Please give it a try. Thanks for the feedback.

**Comment by SuperFrankyy** [comment]
Many thanks! It works.
